bug fix: `split #` fails if the filename of `#` is empty
lambdalisue/gina.vim pull request #223
Opened 2019-08-12 04:14 UTC by reaysawa

closes #211

When you try to `split #` and `bufname('#')` is empty, Neovim will throw this exception:

```
E499: Empty file name for '%' or '#', only works with "p:h"
```

This PR adds and extra check for empty filenames before trying to `split #`.

2019-08-19 09:31 UTC, lambdalisue requested changes

2019-08-19 09:31 UTC, lambdalisue commented on autoload/gina/command/commit.vim
> +    if len(bufname('#')) && bufnr('#') != -1
1. Please use `!empty(bufname('#'))` instead
2. Please use `isnot#` instead of `!=`

2019-08-19 10:30 UTC, reaysawa commented
There you go @lambdalisue

2019-08-20 06:49 UTC, merged

2019-08-20 06:49 UTC, lambdalisue commented
Thank you 👍