Fix buffer number (#91)
lambdalisue/gina.vim pull request #92
Opened 2017-05-03 10:08 UTC by bimlas

0 is the alternate buffer, not the current one.

2017-05-03 11:19 UTC, bimlas commented
As I know it works. Steps of testing:

```
:set signcolumn=auto
:Gina blame :
:sign define piet text=>> texthl=Search | exe ":sign place 2 line=23 name=piet file=" . expand("%:p")
:exe ":sign place 2 line=23 name=piet file=" . expand("%:p")
Press <C-L> on navi
```
(the sign example is taken from `:help :sign`)

2017-05-04 08:52 UTC, lambdalisue requested changes

2017-05-04 08:52 UTC, lambdalisue commented on autoload/gina/command/blame.vim
> +    return len(split(execute('sign place buffer='.bufnr('%')), '\r\?\n')) > 1
Please add spaces around `.` while Vim use `.` for 1) concatenating strings 2) dictionary attribute. Without spaces, it is a bit difficult to distinguish

2017-05-04 09:46 UTC, bimlas commented
Forced push the change.

2017-05-04 09:59 UTC, merged

2017-05-04 09:59 UTC, lambdalisue commented
Thanks a lot!